pipeline {
  agent any

  options {
    timeout(time: 2, unit: 'MINUTES') #Tiempo que puede durar los test
  }

  environment {
    ARTIFACT_ID = "htillero/webapp:${env.BUILD_NUMBER}" #Se define el ARTIFACT_ID
  }

  stages {
    stage('Build') {
      steps {
        script {
          dir("webapp") { #Entra al directorio webapp
            dockerImage = docker.build "${env.ARTIFACT_ID}" #Se hace el build usando el ARTIFACT_ID y lo guardas en la variable dockerImage (comando nativo de jenkins)
          }
        }
      }
    }
    stage('Run tests') {
      steps {
        sh "docker run ${dockerImage.id} npm test" #Comando shell usando la variable dockerImage
      }
    }
    stage('Publish') {
      when {
        branch 'master'
      }
      steps {
        script {
          docker.withRegistry("", "DockerHubCredentials") {
            dockerImage.push()
          }
        }
      }
    }
    stage('Schedule Staging Deployment') {
      when {
        branch 'master'
      }
      steps {
        build job: 'deploy-webapp-staging', parameters: [string(name: 'ARTIFACT_ID', value: "${env.ARTIFACT_ID}")], wait: false
      }
    }
  }
}

